version: '3'
services:
    app:
        build: .
        ports:
            - 3000:3000
        volumes:
            - ./:/code
            - /code/node_modules
    nginx:
        image: nginx:1.13
        ports:
            - 80:80
        links:
            - app:app
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

